/**
 * The sequence of triangle numbers is generated by adding the natural numbers. 
 * 
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred divisors?
 *
 * ANSWER: 76576500
 */
 
public class Problem12 {
	
	public static long triNum(long input){
		long total = 0L;
		for(long i = 1L; i <= input; i++){
			total += i;
		}
		return total;
	}
    
    public static int getFactors(long input){
    	int factors = 0;
    	for(long i = 1L; i <= input; i ++){
    		if(input % i == 0)
    			factors++;
    	}
    	return factors;
    }
    
    public static void main(String[] args) {
    	long answer = 0L;
    	long counter = 1L;
    	while(answer == 0L){
    		if(getFactors(triNum(counter)) > 500)
    			answer = triNum(counter);
    		counter++;
    	}
    	
    	System.out.print(answer);
    }
}
